#!/usr/bin/env node
import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const JS = path.join(ROOT, 'assets/js');
const MAIN = fs.readFileSync(path.join(JS, 'main.js.bak'), 'utf8').split(/\n/);

const mods = ['utils', 'notifications', 'state', 'bookings', 'render', 'cleaning', 'property', 'ai', 'config', 'supabase'];
const symToMod = Object.create(null);

function addExport(mod, name) {
  if (!symToMod[name]) symToMod[name] = mod;
}

for (const mod of mods) {
  const t = fs.readFileSync(path.join(JS, mod + '.js'), 'utf8');
  for (const re of [
    /^export async function (\w+)/gm,
    /^export function (\w+)/gm,
    /^export let (\w+)/gm,
    /^export const (\w+)/gm,
    /^export class (\w+)/gm,
  ]) {
    let m;
    while ((m = re.exec(t))) addExport(mod, m[1]);
  }
  const reStar = /^export \{([^}]+)\}/gm;
  let m;
  while ((m = reStar.exec(t))) {
    m[1].split(',').forEach((part) => {
      const n = part.trim().split(/\s+as\s+/)[0].trim();
      if (n) addExport(mod, n);
    });
  }
}

const tail = MAIN.slice(10140, 10532).join('\n'); // lines 10141-10532
const assigns = [...tail.matchAll(/window\.(\w+)\s*=\s*(\w+);/g)];
const definedInTail = new Set();
for (const m of tail.matchAll(/^(?:async\s+)?function\s+(\w+)\s*\(/gm)) definedInTail.add(m[1]);
const need = new Set();
for (const [, , rhs] of assigns) {
  if (rhs === 'new' || rhs === 'decodeURIComponent') continue;
  if (definedInTail.has(rhs)) continue;
  need.add(rhs);
}

const byMod = Object.create(null);
for (const name of need) {
  const mod = symToMod[name];
  if (!mod) {
    console.error('MISSING symbol for window:', name);
    process.exitCode = 1;
    continue;
  }
  if (!byMod[mod]) byMod[mod] = [];
  byMod[mod].push(name);
}

const importOrder = ['utils', 'notifications', 'state', 'bookings', 'render', 'cleaning', 'property', 'ai', 'config', 'supabase'];

let out = `// Generated by scripts/gen_app_js.mjs — regenerate after module changes.
import './supabase.js';
import './config.js';
import './setup.js';
import './adapter.js';
import './ai-logic.js';

`;

for (const mod of importOrder) {
  const names = (byMod[mod] || []).sort();
  if (!names.length) continue;
  out += `import {\n  ${names.join(',\n  ')}\n} from './${mod}.js';\n`;
}

out += `
import { SupabaseAdapter } from './adapter.js';

`;

out += tail + '\n';

fs.writeFileSync(path.join(JS, 'app.js'), out);
console.log('Wrote assets/js/app.js', 'symbols:', need.size);
