-- ============================================================================
-- StayOps — BASELINE SCHEMA SNAPSHOT
-- Captured from production (project nbeuyypgiipptxlqnhel) on 2026-07-08.
--
-- WHY THIS EXISTS: until now the schema lived only in prod (hand-applied DDL),
-- which caused silent "missing column" save failures. This file is the repo's
-- source of truth for the shape the app code expects.
--
-- SCOPE / CAVEATS: this is a COLUMN-LEVEL baseline (tables, columns, types,
-- defaults, nullability) plus RLS-enable flags. It intentionally does NOT
-- reproduce every constraint, index, foreign key, trigger, RLS *policy*, or
-- function — those still live in prod. It is meant to document + diff the shape,
-- not to stand up a byte-perfect clone. All statements are idempotent
-- (CREATE TABLE IF NOT EXISTS), so re-running against prod is a safe no-op.
--
-- GOING FORWARD: every schema change ships as a new timestamped, idempotent
-- migration in this folder, committed WITH the code that needs it. See README.md.
-- ============================================================================

create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

create table if not exists public.app_config (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  push_subs jsonb default '{}'::jsonb,
  sms_template text,
  email_templates jsonb default '{}'::jsonb,
  expense_cats jsonb default '[]'::jsonb,
  updated_at timestamptz default now(),
  gmail_refresh_token text,
  gmail_email text,
  gmail_connected_at timestamptz,
  gmail_last_scan timestamptz,
  gmail_skipped_ids text,
  push_subscriptions jsonb default '[]'::jsonb,
  active_property_id uuid,
  ui_preferences jsonb default '{}'::jsonb,
  notification_config jsonb default '{}'::jsonb,
  recurring_templates jsonb default '[]'::jsonb,
  depreciation_assets jsonb default '[]'::jsonb,
  cleaner_automation jsonb default '{}'::jsonb,
  clients jsonb default '[]'::jsonb,
  cleaner_learning jsonb default '{}'::jsonb,
  channel_manager_api_key text,
  channel_manager_refresh_token text,
  cancellation_last_seen timestamptz,
  ical_last_sync timestamptz,
  ical_last_error text,
  bank_details jsonb default '{}'::jsonb,
  invoice_details jsonb default '{}'::jsonb,
  invoice_logo text,
  invoices jsonb default '[]'::jsonb,
  ai_ignore jsonb default '[]'::jsonb,
  mgmt_fee_rate numeric default 0,
  auto_assign_cleaner boolean default true,
  email_content_config jsonb default '{}'::jsonb,
  native_push_tokens jsonb default '[]'::jsonb
);

create table if not exists public.bank_import_log (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  import_date timestamptz default now(),
  filename text,
  total_rows integer default 0,
  imported integer default 0,
  skipped integer default 0,
  duplicates integer default 0
);

create table if not exists public.bank_transactions (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  expense_id uuid,
  date date not null,
  amount numeric not null,
  description text not null,
  bank_name text,
  import_batch_id uuid,
  is_personal boolean default false,
  skipped boolean default false,
  created_at timestamptz default now(),
  direction text not null default 'debit'::text
);

create table if not exists public.bookings (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  property_id uuid,
  local_id text,
  checkin date not null,
  checkout date not null,
  nights integer,
  guest_name text,
  guests integer default 1,
  host_payout numeric default 0,
  cleaning_fee numeric default 0,
  mgmt_fee numeric default 0,
  mgmt_fee_raw numeric default 0,
  mgmt_payout numeric default 0,
  net_payout numeric default 0,
  platform text,
  confirmation_code text,
  status text default 'confirmed'::text,
  cleaner_confirmed boolean default false,
  gcal_event_id text,
  source text default 'email'::text,
  raw_email_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  gmail_message_id text,
  email text,
  phone text,
  message text,
  property_unconfirmed boolean default false,
  emails_sent jsonb default '[]'::jsonb,
  return_code text,
  cm_booking_id text,
  cm_synced_at timestamptz,
  booked_at timestamptz,
  ical_uid text,
  ical_feed_id uuid,
  enrichment_status text,
  notes text,
  modification_pending_at timestamptz,
  cancelled_at timestamptz,
  cancellation_billable boolean
);

create table if not exists public.calendar_sync_log (
  id bigint not null generated by default as identity,
  user_id uuid,
  provider text,
  direction text,
  local_table text,
  local_id text,
  provider_event_id text,
  op text,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.calendar_sync_state (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  provider text not null,
  local_table text not null,
  local_id text,
  provider_event_id text not null,
  provider_calendar_id text not null,
  provider_etag text,
  local_updated_at timestamptz,
  provider_updated_at timestamptz,
  last_synced_at timestamptz not null default now(),
  pending_direction text,
  inbox_payload jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.cleaners (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  name text not null,
  email text,
  phone text,
  active boolean default true,
  created_at timestamp default now(),
  local_id text,
  role text default 'Cleaner'::text,
  pin text,
  permissions jsonb,
  updated_at timestamp default now(),
  auth_user_id uuid,
  invitation_status text not null default 'pending'::text
);

create table if not exists public.cleans (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  property_id uuid,
  local_id text,
  booking_id text,
  guest_name text,
  cleaner text,
  cleaner_id text,
  clean_date date,
  done boolean default false,
  cleaner_confirmed boolean default false,
  cleaner_declined boolean default false,
  notified boolean default false,
  assigned_at timestamp,
  confirmed_at timestamp,
  completed_at timestamp,
  notes text,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  reminder_sent boolean default false,
  cleaner_uuid uuid,
  cost numeric,
  cleaner_cancel_notified boolean default false,
  cleaner_cancel_acknowledged boolean default false,
  cleaner_cancel_acknowledged_at timestamptz
);

create table if not exists public.email_connections (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  email text,
  provider text,
  access_token text,
  refresh_token text,
  token_expiry timestamptz,
  platforms text[],
  connected_at timestamptz default now(),
  updated_at timestamptz default now(),
  skipped_ids text default '[]'::text,
  calendar_id text,
  sync_token text,
  watch_channel_id text,
  watch_resource_id text,
  watch_expires_at timestamptz,
  outlook_subscription_id text,
  outlook_client_state text,
  outlook_delta_link text
);

create table if not exists public.expense_email_log (
  id uuid not null default gen_random_uuid(),
  gmail_message_id text not null,
  user_id uuid not null,
  property_id uuid,
  expense_id uuid,
  vendor text,
  amount numeric,
  processed_at timestamptz default now()
);

create table if not exists public.expenses (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  property_id uuid,
  local_id text,
  date date,
  merchant text,
  description text,
  category text,
  amount numeric default 0,
  receipt_num text,
  receipt_type text,
  drive_link text,
  photo text,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  vendor text,
  reconciled boolean default false,
  bank_transaction_id uuid,
  payment_status text default 'unknown'::text,
  booking_id uuid,
  status text not null default 'active'::text,
  tax_note text,
  paid_by text default 'host'::text,
  recoverable_from_owner boolean default false,
  gst numeric
);

create table if not exists public.guest_offers (
  id uuid not null default gen_random_uuid(),
  property_id uuid,
  guest_name text not null,
  email text not null,
  phone text,
  checkin_date date,
  newsletter_opt_in boolean not null default false,
  status text not null default 'pending'::text,
  promo_code text,
  discount_pct integer not null default 5,
  expires_at date,
  redeemed_at timestamptz,
  redeemed_booking_id uuid,
  created_at timestamptz not null default now(),
  approved_at timestamptz
);

create table if not exists public.host_config (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  property_name text,
  beds integer,
  baths integer,
  max_guests integer,
  timezone text default 'Australia/Sydney'::text,
  sheets_url text,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  email text,
  phone text,
  address text,
  company text,
  abn text,
  acn text,
  host_id text,
  name text
);

create table if not exists public.inventory (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  property_id uuid,
  local_id text,
  name text,
  stock integer default 0,
  threshold integer default 0,
  unit text,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

create table if not exists public.maintenance (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  property_id uuid,
  local_id text not null,
  description text not null default ''::text,
  status text not null default 'open'::text,
  cost numeric default 0,
  contractor text default ''::text,
  date date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.messages (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  cleaner_id uuid not null,
  sender_type text not null,
  message_type text not null default 'text'::text,
  body text,
  card_type text,
  card_data jsonb,
  attachment_url text,
  read_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.notes (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  property_id uuid,
  local_id text,
  content text,
  created_at timestamp default now(),
  updated_at timestamp default now()
);

create table if not exists public.notification_log (
  id uuid not null default gen_random_uuid(),
  property_id uuid,
  type text not null,
  reference_id text,
  title text,
  body text,
  sent_at timestamptz default now()
);

create table if not exists public.platform_payout_lines (
  id uuid not null default gen_random_uuid(),
  payout_id uuid not null,
  booking_id uuid,
  line_type text not null,
  description text,
  amount numeric not null default 0,
  confirmation_code text,
  confidence text not null default 'low'::text,
  matched_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.platform_payouts (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  property_id uuid,
  platform text not null,
  payout_reference text,
  payout_date date not null,
  expected_arrival_date date,
  gross_amount numeric not null default 0,
  platform_fee numeric not null default 0,
  adjustments numeric not null default 0,
  net_amount numeric not null default 0,
  currency text not null default 'AUD'::text,
  source text not null default 'manual'::text,
  raw_source_text text,
  bank_transaction_id uuid,
  status text not null default 'active'::text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  received_at date
);

create table if not exists public.price_overrides (
  id uuid not null default gen_random_uuid(),
  property_id uuid not null,
  date date not null,
  price numeric not null,
  created_at timestamptz default now()
);

create table if not exists public.pricing_rules (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  property_id uuid not null,
  rule_type text not null,
  name text,
  value numeric not null default 0,
  condition_type text,
  condition_value numeric,
  is_default boolean not null default false,
  meta jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pricing_runs (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  property_id uuid not null,
  forecast_start date not null,
  forecast_end date not null,
  trigger text not null default 'manual'::text,
  model text,
  prompt_tokens integer,
  completion_tokens integer,
  insight text,
  raw_response jsonb,
  error text,
  created_at timestamptz not null default now()
);

create table if not exists public.pricing_suggestions (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  property_id uuid not null,
  run_id uuid not null,
  date date not null,
  suggested_rate numeric not null default 0,
  rate_type text,
  reason text,
  signals jsonb,
  generated_at timestamptz not null default now()
);

create table if not exists public.properties (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  name text not null,
  address text,
  suburb text,
  state text,
  country text default 'Australia'::text,
  bedrooms integer default 0,
  bathrooms numeric default 0,
  max_guests integer default 0,
  timezone text default 'Australia/Sydney'::text,
  sheets_url text,
  script_url text,
  base_rate numeric default 0,
  property_type text default 'house'::text,
  tagline text,
  region text,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  drive_client_id text,
  drive_folder_id text,
  calendar_id text default 'primary'::text,
  vapid_public_key text,
  anthropic_api_key text,
  owner_name text,
  owner_email text,
  owner_phone text,
  report_email_subject text,
  report_email_body text,
  auto_send_report boolean default false,
  report_frequency text default 'monthly'::text,
  last_report_sent_at timestamptz,
  mgmt_fee_rate numeric default 0,
  check_in_info jsonb default '{}'::jsonb,
  airbnb_listing_id text,
  airbnb_listing_url text,
  airbnb_listing_title text,
  booking_com_url text,
  platforms jsonb default '[]'::jsonb,
  stayz_url text,
  vrbo_url text,
  latitude numeric,
  longitude numeric,
  is_self_managed boolean default true
);

create table if not exists public.property_ical_feeds (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  property_id uuid not null,
  platform text not null,
  ical_url text not null,
  active boolean not null default true,
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  label text
);

create table if not exists public.rate_outcomes (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  property_id uuid not null,
  date date not null,
  suggested_rate numeric,
  rate_type text,
  actual_rate numeric,
  booked boolean not null default false,
  booking_cloud_id uuid,
  closed_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid not null default gen_random_uuid(),
  property_id uuid,
  booking_id uuid,
  return_code text,
  guest_name text not null,
  rating integer not null,
  review_text text not null,
  stay_date text,
  status text not null default 'pending'::text,
  created_at timestamptz default now(),
  platform text default 'direct'::text
);

create table if not exists public.scan_debug (
  id bigint not null generated by default as identity,
  user_id uuid,
  msg_id text,
  subject text,
  email_from text,
  body_len integer,
  body_excerpt text,
  parsed jsonb,
  email_type text,
  created_at timestamptz default now()
);

create table if not exists public.site_config (
  id uuid not null default gen_random_uuid(),
  property_id uuid,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.user_roles (
  id uuid not null default gen_random_uuid(),
  auth_user_id uuid not null,
  role text not null,
  created_at timestamptz default now()
);

create table if not exists public.vendor_mappings (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  vendor_pattern text not null,
  property_id uuid,
  category text,
  is_personal boolean default false,
  times_used integer default 1,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Row-Level Security is ENABLED on every public table in prod (verified 2026-07-08).
-- (Policies themselves are not reproduced here — see README.md.)
alter table public.app_config            enable row level security;
alter table public.bank_import_log       enable row level security;
alter table public.bank_transactions     enable row level security;
alter table public.bookings              enable row level security;
alter table public.calendar_sync_log     enable row level security;
alter table public.calendar_sync_state   enable row level security;
alter table public.cleaners              enable row level security;
alter table public.cleans                enable row level security;
alter table public.email_connections     enable row level security;
alter table public.expense_email_log     enable row level security;
alter table public.expenses              enable row level security;
alter table public.guest_offers          enable row level security;
alter table public.host_config           enable row level security;
alter table public.inventory             enable row level security;
alter table public.maintenance           enable row level security;
alter table public.messages              enable row level security;
alter table public.notes                 enable row level security;
alter table public.notification_log      enable row level security;
alter table public.platform_payout_lines enable row level security;
alter table public.platform_payouts      enable row level security;
alter table public.price_overrides       enable row level security;
alter table public.pricing_rules         enable row level security;
alter table public.pricing_runs          enable row level security;
alter table public.pricing_suggestions   enable row level security;
alter table public.properties            enable row level security;
alter table public.property_ical_feeds   enable row level security;
alter table public.rate_outcomes         enable row level security;
alter table public.reviews               enable row level security;
alter table public.scan_debug            enable row level security;
alter table public.site_config           enable row level security;
alter table public.user_roles            enable row level security;
alter table public.vendor_mappings       enable row level security;
